openapi: 3.0.0
info:
  description: API for predicting and evaluating metabolite separation configurations.
  title: Metabolite Separation API
  version: 1.0.0
servers:
- url: /
paths:
  /predict:
    post:
      description: "Given a metabolite family, it returns the best configuration to\
        \ separate them."
      operationId: predictPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FamilyRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PredictResponse'
          description: Configuration predicted successfully.
        "400":
          description: "Bad request, missing or incorrect \"family\" field."
        "404":
          description: Metabolite family not found.
      summary: Predicts the best configuration to separate a metabolite family.
      x-eov-operation-handler: controllers/DefaultController
  /evaluate:
    post:
      description: Evaluates how good a configuration is for a metabolite family by
        calculating the alpha score.
      operationId: evaluatePOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EvaluateRequest'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EvaluateResponse'
          description: Alpha evaluation completed successfully.
        "400":
          description: "Bad request, missing or incorrect fields."
        "404":
          description: Metabolite family not found.
      summary: Evaluates the alpha score for a given configuration.
      x-eov-operation-handler: controllers/DefaultController
  /families:
    get:
      description: Returns a list of available metabolite families for the system.
      operationId: familiesGET
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                type: array
          description: Successfully retrieved metabolite families.
        "404":
          description: No metabolite families found.
      summary: Retrieves a list of metabolite families.
      x-eov-operation-handler: controllers/DefaultController
  /experiments:
    post:
      description: Adds new experiment data to the system.
      operationId: experimentsPOST
      requestBody:
        content:
          application/json:
            schema:
              #$ref: '#/components/schemas/ExperimentRequest'
              $ref: '#/components/schemas/ExperimentRequestList'
      responses:
        "200":
          description: Experiment data added successfully.
        "400":
          description: "Bad request, missing or incorrect fields."
      summary: Adds an experiment to the database.
      x-eov-operation-handler: controllers/DefaultController
  /recommendFamily:
    post:
      description: "Given a configuration, recommends the most appropriate metabolite\
        \ family."
      operationId: recommendFamilyPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Configuration'
      responses:
        "200":
          description: Metabolite family recommended successfully.
        "400":
          description: "Bad request, missing or incorrect \"configuration\"."
        "404":
          description: No suitable metabolite family found.
      summary: Recommends the most suitable metabolite family for a given configuration.
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    FamilyRequest:
      example:
        family: family
      properties:
        family:
          description: The metabolite family to evaluate.
          type: string
      required:
      - family
      type: object
    Column:
      description: Predicted chromatographic column configuration.
      example:
        length: 1.4658129805029452
        name: name
        temperature: 5.637376656633329
        particleSize: 5.962133916683182
        flowrate: 2.3021358869347655
        t0: 7.061401241503109
        uspCode: uspCode
      properties:
        uspCode:
          type: string
        length:
          type: number
        name:
          type: string
        particleSize:
          type: number
        temperature:
          type: number
        flowrate:
          type: number
        t0:
          type: number
      type: object
    GradientOption1:
      example:
        x8: 6.84685269835264
        duration: 4.965218492984954
        x9: 7.457744773683766
        x10: 1.1730742509559433
        x0: 9.301444243932576
        x1: 3.616076749251911
        x2: 2.027123023002322
        x3: 4.145608029883936
        x4: 7.386281948385884
        x5: 1.2315135367772556
        x6: 1.0246457001441578
        x7: 1.4894159098541704
      properties:
        x0:
          type: number
        x1:
          type: number
        x2:
          type: number
        x3:
          type: number
        x4:
          type: number
        x5:
          type: number
        x6:
          type: number
        x7:
          type: number
        x8:
          type: number
        x9:
          type: number
        x10:
          type: number
        duration:
          type: number
      required:
      - duration
      - x0
      - x1
      - x10
      - x2
      - x3
      - x4
      - x5
      - x6
      - x7
      - x8
      - x9
      type: object
    GradientOption2:
      properties:
        eluent1Gradient:
          items:
            type: number
          type: array
        eluent2Gradient:
          items:
            type: number
          type: array
        timeGradient:
          items:
            type: number
          type: array
      required:
      - eluent1Gradient
      - eluent2Gradient
      - timeGradient
      type: object
    Gradient:
      description: Predicted gradient configuration for separation.
      oneOf:
      - $ref: '#/components/schemas/GradientOption1'
      - $ref: '#/components/schemas/GradientOption2'
    Configuration:
      description: Predicted configuration for separating the metabolite family.
      example:
        eluent2: eluent2
        eluent1: eluent1
        gradient:
          x8: 6.84685269835264
          duration: 4.965218492984954
          x9: 7.457744773683766
          x10: 1.1730742509559433
          x0: 9.301444243932576
          x1: 3.616076749251911
          x2: 2.027123023002322
          x3: 4.145608029883936
          x4: 7.386281948385884
          x5: 1.2315135367772556
          x6: 1.0246457001441578
          x7: 1.4894159098541704
        ph1: 0.8008281904610115
        column:
          length: 1.4658129805029452
          name: name
          temperature: 5.637376656633329
          particleSize: 5.962133916683182
          flowrate: 2.3021358869347655
          t0: 7.061401241503109
          uspCode: uspCode
        ph2: 6.027456183070403
      properties:
        eluent1:
          type: string
        eluent2:
          type: string
        ph1:
          type: number
        ph2:
          type: number
        column:
          $ref: '#/components/schemas/Column'
        gradient:
          $ref: '#/components/schemas/Gradient'
      type: object
    PredictResponse:
      example:
        score: 5.025004791520295
        configuration:
          eluent2: eluent2
          eluent1: eluent1
          gradient:
            x8: 6.84685269835264
            duration: 4.965218492984954
            x9: 7.457744773683766
            x10: 1.1730742509559433
            x0: 9.301444243932576
            x1: 3.616076749251911
            x2: 2.027123023002322
            x3: 4.145608029883936
            x4: 7.386281948385884
            x5: 1.2315135367772556
            x6: 1.0246457001441578
            x7: 1.4894159098541704
          ph1: 0.8008281904610115
          column:
            length: 1.4658129805029452
            name: name
            temperature: 5.637376656633329
            particleSize: 5.962133916683182
            flowrate: 2.3021358869347655
            t0: 7.061401241503109
            uspCode: uspCode
          ph2: 6.027456183070403
        family: family
      properties:
        family:
          description: The metabolite family evaluated.
          type: string
        configuration:
          $ref: '#/components/schemas/Configuration'
        score:
          type: number
      required:
      - configuration
      - family
      - score
      type: object
    EvaluateRequest:
      example:
        configuration:
          eluent2: eluent2
          eluent1: eluent1
          gradient:
            x8: 6.84685269835264
            duration: 4.965218492984954
            x9: 7.457744773683766
            x10: 1.1730742509559433
            x0: 9.301444243932576
            x1: 3.616076749251911
            x2: 2.027123023002322
            x3: 4.145608029883936
            x4: 7.386281948385884
            x5: 1.2315135367772556
            x6: 1.0246457001441578
            x7: 1.4894159098541704
          ph1: 0.8008281904610115
          column:
            length: 1.4658129805029452
            name: name
            temperature: 5.637376656633329
            particleSize: 5.962133916683182
            flowrate: 2.3021358869347655
            t0: 7.061401241503109
            uspCode: uspCode
          ph2: 6.027456183070403
        family: family
      properties:
        family:
          description: The metabolite family evaluated.
          type: string
        configuration:
          $ref: '#/components/schemas/Configuration'
      required:
      - configuration
      - family
      type: object
    EvaluateResponse:
      example:
        score: 0.8008281904610115
      properties:
        score:
          description: The score relative to how good the configuration separates
            this metabolite family.
          type: number
      type: object
    ExperimentRequestList:
      type: array
      items:
        $ref: '#/components/schemas/ExperimentRequest'
    ExperimentRequest:
      example:
        rt: 0.8008282
        gradiente:
          t_gradiente:
          - 7.061401241503109
          - 7.061401241503109
          eluyente2: eluyente2
          eluyente2_gradiente:
          - 0.6
          - 1.0
          ph1: 9.301444
          eluyente1: eluyente1
          eluyente1_gradiente:
          - 0.4
          - 0.0
          ph2: 3.6160767
        alternative_parents: alternative_parents
        smiles_std: smiles_std
        column:
          usp_code: usp_code
          name: name
          length: 6
          particle_size: 1.4658129
          temperature: 5.962134
          flowrate: 5.637377
          t0: 2.302136
        formula: formula
        comment: comment
        inchi_std: inchi_std
        name_metabolito: name_metabolito
        classyfire:
          level5: level5
          level6: level6
          superclass: superclass
          subclass: subclass
          kingdom: kingdom
          class: class
        inchikey_std: inchikey_std
      properties:
        name_metabolito:
          type: string
        formula:
          type: string
        rt:
          format: float
          type: number
        smiles_std:
          type: string
        inchi_std:
          type: string
        inchikey_std:
          type: string
        classyfire:
          $ref: '#/components/schemas/ExperimentRequest_classyfire'
        comment:
          type: string
        alternative_parents:
          type: string
        column:
          $ref: '#/components/schemas/ExperimentRequest_column'
        gradiente:
          $ref: '#/components/schemas/ExperimentRequest_gradiente'
      type: object
    ExperimentRequest_classyfire:
      example:
        level5: level5
        level6: level6
        superclass: superclass
        subclass: subclass
        kingdom: kingdom
        class: class
      properties:
        kingdom:
          type: string
        superclass:
          type: string
        class:
          type: string
        subclass:
          type: string
        level5:
          type: string
        level6:
          type: string
      type: object
    ExperimentRequest_column:
      example:
        usp_code: usp_code
        name: name
        length: 6
        particle_size: 1.4658129
        temperature: 5.962134
        flowrate: 5.637377
        t0: 2.302136
      properties:
        name:
          type: string
        usp_code:
          type: string
        length:
          type: integer
        particle_size:
          format: float
          type: number
        temperature:
          format: float
          type: number
        flowrate:
          format: float
          type: number
        t0:
          format: float
          type: number
      type: object
    ExperimentRequest_gradiente:
      example:
        t_gradiente:
        - 7.061401241503109
        - 7.061401241503109
        eluyente2: eluyente2
        eluyente2_gradiente:
          - 0.4
          - 0.0
        ph1: 9.301444
        eluyente1: eluyente1
        eluyente1_gradiente:
          - 0.6
          - 1.0
        ph2: 3.6160767
      properties:
        eluyente1:
          type: string
        eluu_gradiente:
          items:
            type: number
          type: array
        eluyente2:
          type: string
        t_gradiente:
          items:
            type: number
          type: array
        ph1:
          format: float
          type: number
        ph2:
          format: float
          type: number
      type: object
